package main

import (
	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode"

	"github.com/getsentry/sentry-go"
	"github.com/pocketbase/pocketbase"
	"github.com/pocketbase/pocketbase/core"
	"github.com/pocketbase/pocketbase/plugins/jsvm"
	"github.com/pocketbase/pocketbase/plugins/migratecmd"
	"github.com/pocketbase/pocketbase/tools/hook"
)

const defaultHTTPAddr = "127.0.0.1:7090"

func main() {
	loadEnvFile()

	// Default to port 7090 if --http is not explicitly provided (serve only)
	if hasSubcommand("serve") && !hasFlag("--http") {
		os.Args = append(os.Args, "--http", defaultHTTPAddr)
	}

	if err := sentry.Init(sentry.ClientOptions{
		Dsn:              os.Getenv("SENTRY_DSN"),
		Environment:      getEnvironment(),
		TracesSampleRate: 0.2,
		AttachStacktrace: true,
	}); err != nil {
		log.Printf("Sentry initialization failed: %v", err)
	}
	defer sentry.Flush(2 * time.Second)

	app := pocketbase.New()

	// ---------------------------------------------------------------
	// Optional plugin flags:
	// ---------------------------------------------------------------

	var hooksDir string
	app.RootCmd.PersistentFlags().StringVar(
		&hooksDir,
		"hooksDir",
		"",
		"the directory with the JS app hooks",
	)

	var hooksWatch bool
	app.RootCmd.PersistentFlags().BoolVar(
		&hooksWatch,
		"hooksWatch",
		true,
		"auto restart the app on pb_hooks file change; it has no effect on Windows",
	)

	var hooksPool int
	app.RootCmd.PersistentFlags().IntVar(
		&hooksPool,
		"hooksPool",
		15,
		"the total prewarm goja.Runtime instances for the JS app hooks execution",
	)

	var migrationsDir string
	app.RootCmd.PersistentFlags().StringVar(
		&migrationsDir,
		"migrationsDir",
		"",
		"the directory with the user defined migrations",
	)

	var automigrate bool
	app.RootCmd.PersistentFlags().BoolVar(
		&automigrate,
		"automigrate",
		true,
		"enable/disable auto migrations",
	)

	var publicDir string
	app.RootCmd.PersistentFlags().StringVar(
		&publicDir,
		"publicDir",
		defaultPublicDir(),
		"the directory to serve static files",
	)

	var fallbackFile string
	app.RootCmd.PersistentFlags().StringVar(
		&fallbackFile,
		"fallbackFile",
		"app.html",
		"fallback to this file on missing static path for SPA routes",
	)

	var typesDir string
	app.RootCmd.PersistentFlags().StringVar(
		&typesDir,
		"typesDir",
		defaultTypesDir(),
		"the directory to write generated TypeScript schema files",
	)

	app.RootCmd.ParseFlags(os.Args[1:])

	// ---------------------------------------------------------------
	// Plugins and hooks:
	// ---------------------------------------------------------------

	// load jsvm (pb_hooks and pb_migrations)
	jsvm.MustRegister(app, jsvm.Config{
		MigrationsDir: migrationsDir,
		HooksDir:      hooksDir,
		HooksWatch:    hooksWatch,
		HooksPoolSize: hooksPool,
	})

	// migrate command (with js templates)
	migratecmd.MustRegister(app, app.RootCmd, migratecmd.Config{
		TemplateLang: migratecmd.TemplateLangJS,
		Automigrate:  automigrate,
		Dir:          migrationsDir,
	})

	// Register addon server extensions (generated by scripts/generate-addons.ts)
	registerAddonExtensions(app)

	// ---------------------------------------------------------------
	// Schema generation hooks
	// ---------------------------------------------------------------
	app.OnCollectionCreateRequest().BindFunc(func(e *core.CollectionRequestEvent) error {
		if err := e.Next(); err != nil {
			return err
		}
		generateSchemas(e.App, typesDir)
		return nil
	})

	app.OnCollectionUpdateRequest().BindFunc(func(e *core.CollectionRequestEvent) error {
		if err := e.Next(); err != nil {
			return err
		}
		generateSchemas(e.App, typesDir)
		return nil
	})

	app.OnCollectionDeleteRequest().BindFunc(func(e *core.CollectionRequestEvent) error {
		if err := e.Next(); err != nil {
			return err
		}
		generateSchemas(e.App, typesDir)
		return nil
	})

	// static route to serves files from the provided public dir
	// (if publicDir exists and the route path is not already defined)
	app.OnServe().Bind(&hook.Handler[*core.ServeEvent]{
		Func: func(e *core.ServeEvent) error {
			generateSchemas(e.App, typesDir)

			e.Router.POST("/api/signup", HandleSignup)

			if !e.Router.HasRoute(http.MethodGet, "/{path...}") {
				e.Router.Any("/{path...}", staticWithFallback(publicDir, fallbackFile))
			}

			return e.Next()
		},
		Priority: 999,
	})

	if err := app.Start(); err != nil {
		log.Fatal(err)
	}
}

// the default public dir location is relative to the executable
func defaultPublicDir() string {
	if strings.HasPrefix(os.Args[0], os.TempDir()) {
		// most likely ran with go run
		return "./public"
	}

	return filepath.Join(os.Args[0], "../public")
}

func defaultTypesDir() string {
	if strings.HasPrefix(os.Args[0], os.TempDir()) {
		return "../types"
	}
	return filepath.Join(os.Args[0], "../../types")
}

func hasFlag(name string) bool {
	for _, arg := range os.Args[1:] {
		if arg == name || strings.HasPrefix(arg, name+"=") {
			return true
		}
	}
	return false
}

func hasSubcommand(name string) bool {
	for _, arg := range os.Args[1:] {
		if !strings.HasPrefix(arg, "-") && arg == name {
			return true
		}
	}
	return false
}

func getEnvironment() string {
	if env := os.Getenv("ENVIRONMENT"); env != "" {
		return env
	}
	for _, arg := range os.Args {
		if arg == "--dev" {
			return "development"
		}
	}
	return "production"
}

// staticWithFallback serves static files from dir, falling back to fallbackFile for missing paths
func staticWithFallback(dir string, fallbackFile string) func(*core.RequestEvent) error {
	fs := os.DirFS(dir)

	return func(e *core.RequestEvent) error {
		// Only serve static files for GET/HEAD — let WebDAV methods pass through
		if e.Request.Method != http.MethodGet && e.Request.Method != http.MethodHead {
			return e.Next()
		}

		path := e.Request.PathValue("path")
		if path == "" {
			path = "index.html"
		}

		// Try to open the requested file
		f, err := fs.Open(path)
		if err == nil {
			f.Close()
			return e.FileFS(fs, path)
		}

		// Try path/index.html for directory-style routes (e.g. /features -> features/index.html)
		indexPath := path + "/index.html"
		f, err = fs.Open(indexPath)
		if err == nil {
			f.Close()
			return e.FileFS(fs, indexPath)
		}

		// If fallback is configured and file doesn't exist, serve the fallback
		if fallbackFile != "" {
			return e.FileFS(fs, fallbackFile)
		}

		return e.NotFoundError("", nil)
	}
}

// ---------------------------------------------------------------
// Schema generation
// ---------------------------------------------------------------

func generateSchemas(app core.App, typesDir string) {
	collections, err := app.FindAllCollections()
	if err != nil {
		log.Printf("Schema generation: failed to find collections: %v", err)
		return
	}

	// Filter out system collections
	var filtered []*core.Collection
	for _, c := range collections {
		if !c.System {
			filtered = append(filtered, c)
		}
	}

	// Sort by name for deterministic output
	sort.Slice(filtered, func(i, j int) bool {
		return filtered[i].Name < filtered[j].Name
	})

	tsSchema := generateTsSchema(filtered)
	zodSchema := generateZodSchema(filtered)

	if err := os.MkdirAll(typesDir, 0o755); err != nil {
		log.Printf("Schema generation: failed to create types dir: %v", err)
		return
	}

	tsPath := filepath.Join(typesDir, "pbSchema.ts")
	zodPath := filepath.Join(typesDir, "pbZodSchema.ts")

	if err := os.WriteFile(tsPath, []byte(tsSchema), 0o644); err != nil {
		log.Printf("Schema generation: failed to write %s: %v", tsPath, err)
	} else {
		log.Printf("Schema generation: wrote %s", tsPath)
	}

	if err := os.WriteFile(zodPath, []byte(zodSchema), 0o644); err != nil {
		log.Printf("Schema generation: failed to write %s: %v", zodPath, err)
	} else {
		log.Printf("Schema generation: wrote %s", zodPath)
	}
}

// ---------------------------------------------------------------
// TypeScript schema generation
// ---------------------------------------------------------------

func generateTsSchema(collections []*core.Collection) string {
	collectionIDToName := make(map[string]string)
	for _, c := range collections {
		collectionIDToName[c.Id] = c.Name
	}

	var sb strings.Builder

	// Unique identifier tracking
	type fieldSet []string
	var allFieldSets []fieldSet
	needsUniqueIdentifier := false

	for _, collection := range collections {
		var fields fieldSet
		sb.WriteString(fmt.Sprintf("export interface %s {\n", toPascalCase(collection.Name)))

		for _, field := range collection.Fields {
			typeDef := tsFieldType(field, collectionIDToName)
			sb.WriteString(fmt.Sprintf("    %s\n", typeDef))
			fields = append(fields, typeDef)
		}

		// Check if this field set duplicates a previous one
		for _, prev := range allFieldSets {
			if sameStringSlice(prev, fields) {
				needsUniqueIdentifier = true
				sb.WriteString("    readonly [uniqueIdentifier]: unique symbol\n")
				break
			}
		}

		sb.WriteString("}\n\n")
		allFieldSets = append(allFieldSets, fields)
	}

	result := sb.String()
	if needsUniqueIdentifier {
		result = "declare const uniqueIdentifier: unique symbol\n\n" + result
	}

	// Generate Schema type
	result += generatePbTsSchema(collections, collectionIDToName)

	return formatTS(result)
}

func tsFieldType(field core.Field, collectionIDToName map[string]string) string {
	name := field.GetName()

	switch f := field.(type) {
	case *core.TextField:
		return fmt.Sprintf("%s: string", name)
	case *core.PasswordField:
		return fmt.Sprintf("%s: string", name)
	case *core.EditorField:
		return fmt.Sprintf("%s: string", name)
	case *core.NumberField:
		return fmt.Sprintf("%s: number", name)
	case *core.BoolField:
		if f.Required {
			return fmt.Sprintf("%s: true", name)
		}
		return fmt.Sprintf("%s: boolean", name)
	case *core.EmailField:
		return fmt.Sprintf("%s: string", name)
	case *core.URLField:
		return fmt.Sprintf("%s: string", name)
	case *core.DateField:
		return fmt.Sprintf("%s: string", name)
	case *core.AutodateField:
		return fmt.Sprintf("%s: string", name)
	case *core.SelectField:
		options := make([]string, len(f.Values))
		for i, v := range f.Values {
			options[i] = fmt.Sprintf("'%s'", v)
		}
		optionsStr := strings.Join(options, " | ")
		if f.MaxSelect > 1 {
			if f.Required {
				return fmt.Sprintf("%s: [%s, ...(%s)[]]", name, optionsStr, optionsStr)
			}
			return fmt.Sprintf("%s: (%s)[]", name, optionsStr)
		}
		return fmt.Sprintf("%s: %s", name, optionsStr)
	case *core.FileField:
		if f.MaxSelect > 1 {
			if f.Required {
				return fmt.Sprintf("%s: [string, ...string[]]", name)
			}
			return fmt.Sprintf("%s: string[]", name)
		}
		return fmt.Sprintf("%s: string", name)
	case *core.RelationField:
		if f.MaxSelect > 1 {
			if f.Required {
				return fmt.Sprintf("%s: [string, ...string[]]", name)
			}
			return fmt.Sprintf("%s: string[]", name)
		}
		return fmt.Sprintf("%s: string", name)
	case *core.JSONField:
		return fmt.Sprintf("%s: any", name)
	case *core.GeoPointField:
		return fmt.Sprintf("%s: { lon: number; lat: number }", name)
	default:
		return fmt.Sprintf("%s: any", name)
	}
}

func generatePbTsSchema(collections []*core.Collection, collectionIDToName map[string]string) string {
	type relation struct {
		line string
	}

	relationMap := make(map[string][]string)
	for _, c := range collections {
		relationMap[c.Name] = nil
	}

	for _, collection := range collections {
		// Find fields with unique index
		uniqueFields := make(map[string]bool)
		for _, idxStr := range collection.Indexes {
			if strings.Contains(idxStr, "UNIQUE") && !strings.Contains(idxStr, ",") {
				re := regexp.MustCompile(`CREATE UNIQUE.+\(` + "`?" + `([^` + "`" + `\s]+).*\)`)
				matches := re.FindStringSubmatch(idxStr)
				if len(matches) > 1 {
					uniqueFields[matches[1]] = true
				}
			}
		}

		for _, field := range collection.Fields {
			rf, ok := field.(*core.RelationField)
			if !ok {
				continue
			}

			relatedName, exists := collectionIDToName[rf.CollectionId]
			if !exists {
				continue
			}

			// Forward relation
			optionalMark := ""
			if !rf.Required {
				optionalMark = "?"
			}
			suffix := ""
			if rf.MaxSelect > 1 {
				suffix = "[]"
			}
			forward := fmt.Sprintf("%s%s: %s%s", rf.GetName(), optionalMark, toPascalCase(relatedName), suffix)
			relationMap[collection.Name] = append(relationMap[collection.Name], forward)

			// Back relation
			hasUnique := uniqueFields[rf.GetName()]
			backRelation := fmt.Sprintf("%s_via_%s?: %s", collection.Name, rf.GetName(), toPascalCase(collection.Name))
			if !hasUnique {
				backRelation = "// " + backRelation + "[]"
			}
			relationMap[relatedName] = append(relationMap[relatedName], backRelation)
		}
	}

	var sb strings.Builder
	sb.WriteString(`
/**
 * Commented-out back-relations are what will be inferred by pocketbase-ts from the forward relations.
 *
 * The "UNIQUE index constraint" case is automatically handled by this hook,
 * but if you want to make a back-relation non-nullable, you can uncomment it and remove the "?".
 *
 * See https://github.com/satohshi/pocketbase-ts#back-relations for more information.
 */
export type Schema = {
`)

	for _, c := range collections {
		sb.WriteString(fmt.Sprintf("    %s: {\n", c.Name))
		sb.WriteString(fmt.Sprintf("        type: %s\n", toPascalCase(c.Name)))

		relations := relationMap[c.Name]
		if len(relations) > 0 {
			sb.WriteString("        relations: {\n")
			for _, rel := range relations {
				sb.WriteString(fmt.Sprintf("            %s\n", rel))
			}
			sb.WriteString("        }\n")
		}

		sb.WriteString("    }\n")
	}

	sb.WriteString("}\n")
	return sb.String()
}

// ---------------------------------------------------------------
// Zod schema generation
// ---------------------------------------------------------------

func generateZodSchema(collections []*core.Collection) string {
	collectionIDToIDSchema := make(map[string]string)
	for _, c := range collections {
		for _, field := range c.Fields {
			if field.GetName() == "id" {
				if tf, ok := field.(*core.TextField); ok {
					collectionIDToIDSchema[c.Id] = zodTextFieldSchema(tf)
				}
				break
			}
		}
	}

	hasDate := false
	for _, c := range collections {
		for _, field := range c.Fields {
			switch field.(type) {
			case *core.DateField, *core.AutodateField:
				hasDate = true
			}
		}
	}

	var sb strings.Builder
	sb.WriteString("import { z } from 'zod'\n\n")
	if hasDate {
		sb.WriteString(`const DATETIME_REGEX = /^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}(\.\d+)?Z$/`)
		sb.WriteString("\n\n")
	}

	for _, collection := range collections {
		sb.WriteString(fmt.Sprintf("export const %sSchema = z.object({\n", toCamelCase(collection.Name)))

		for _, field := range collection.Fields {
			optional := isZodOptional(field)
			zodType := zodFieldType(field, collectionIDToIDSchema)
			optionalSuffix := ""
			if optional {
				optionalSuffix = ".optional()"
			}
			sb.WriteString(fmt.Sprintf("    %s%s,\n", zodType, optionalSuffix))
		}

		sb.WriteString("})\n\n")
	}

	return sb.String()
}

func isZodOptional(field core.Field) bool {
	switch f := field.(type) {
	case *core.TextField:
		return !f.Required || f.AutogeneratePattern != ""
	case *core.PasswordField:
		return !f.Required
	case *core.EditorField:
		return !f.Required
	case *core.NumberField:
		return !f.Required
	case *core.BoolField:
		return !f.Required
	case *core.EmailField:
		return !f.Required
	case *core.URLField:
		return !f.Required
	case *core.DateField:
		return !f.Required
	case *core.AutodateField:
		return true // autodates are always auto-generated
	case *core.SelectField:
		return !f.Required
	case *core.FileField:
		return !f.Required
	case *core.RelationField:
		return !f.Required
	case *core.JSONField:
		return !f.Required
	case *core.GeoPointField:
		return !f.Required
	default:
		return true
	}
}

func zodFieldType(field core.Field, collectionIDToIDSchema map[string]string) string {
	name := field.GetName()

	switch f := field.(type) {
	case *core.TextField:
		return zodTextFieldSchemaWithName(f)
	case *core.PasswordField:
		// Same as text
		schema := fmt.Sprintf("%s: z.string()", name)
		if f.Min > 0 && f.Min == f.Max {
			schema += fmt.Sprintf(".length(%d)", f.Min)
		} else {
			if f.Min > 0 {
				schema += fmt.Sprintf(".min(%d)", f.Min)
			} else if f.Required {
				schema += ".min(1)"
			}
			if f.Max > 0 {
				schema += fmt.Sprintf(".max(%d)", f.Max)
			}
		}
		return schema
	case *core.EditorField:
		schema := fmt.Sprintf("%s: z.string()", name)
		if f.Required {
			schema += ".min(1)"
		}
		return schema
	case *core.NumberField:
		schema := fmt.Sprintf("%s: z.number()", name)
		if f.OnlyInt {
			schema += ".int()"
		}
		if f.Min != nil && *f.Min != 0 {
			schema += fmt.Sprintf(".min(%g)", *f.Min)
		}
		if f.Max != nil && *f.Max != 0 {
			schema += fmt.Sprintf(".max(%g)", *f.Max)
		}
		if f.Required {
			schema += ".refine((n) => n !== 0)"
		}
		return schema
	case *core.BoolField:
		if f.Required {
			return fmt.Sprintf("%s: z.literal(true)", name)
		}
		return fmt.Sprintf("%s: z.boolean()", name)
	case *core.EmailField:
		schema := fmt.Sprintf("%s: z.string().email()", name)
		if len(f.OnlyDomains) > 0 {
			domains := quotedJoin(f.OnlyDomains)
			schema += fmt.Sprintf(`.refine((v) => [%s].includes(v.split('@')[1]))`, domains)
		} else if len(f.ExceptDomains) > 0 {
			domains := quotedJoin(f.ExceptDomains)
			schema += fmt.Sprintf(`.refine((v) => ![%s].includes(v.split('@')[1]))`, domains)
		}
		return schema
	case *core.URLField:
		schema := fmt.Sprintf("%s: z.string().url()", name)
		if len(f.OnlyDomains) > 0 {
			domains := quotedJoin(f.OnlyDomains)
			schema += fmt.Sprintf(`.refine((v) => [%s].some((domain) => v.includes(domain)))`, domains)
		} else if len(f.ExceptDomains) > 0 {
			domains := quotedJoin(f.ExceptDomains)
			schema += fmt.Sprintf(`.refine((v) => [%s].every((domain) => !v.includes(domain)))`, domains)
		}
		return schema
	case *core.DateField:
		return fmt.Sprintf("%s: z.string().regex(DATETIME_REGEX)", name)
	case *core.AutodateField:
		return fmt.Sprintf("%s: z.string().regex(DATETIME_REGEX)", name)
	case *core.SelectField:
		values := make([]string, len(f.Values))
		for i, v := range f.Values {
			values[i] = fmt.Sprintf(`"%s"`, v)
		}
		schema := fmt.Sprintf("%s: z.enum([%s])", name, strings.Join(values, ", "))
		if f.MaxSelect > 1 {
			schema += ".array()"
			if f.Required {
				schema += ".nonempty()"
			}
			if f.MaxSelect > 0 {
				schema += fmt.Sprintf(".max(%d)", f.MaxSelect)
			}
		}
		return schema
	case *core.FileField:
		schema := fmt.Sprintf("%s: z.string()", name)
		if f.MaxSelect > 1 {
			schema += ".array()"
			if f.Required {
				schema += ".nonempty()"
			}
			if f.MaxSelect > 0 {
				schema += fmt.Sprintf(".max(%d)", f.MaxSelect)
			}
		}
		return schema
	case *core.RelationField:
		targetSchema := "z.string()"
		if idSchema, ok := collectionIDToIDSchema[f.CollectionId]; ok {
			targetSchema = idSchema
		}
		// Remove the "id: " prefix if present
		targetSchema = strings.TrimPrefix(targetSchema, "id: ")
		schema := fmt.Sprintf("%s: %s", name, targetSchema)
		if f.MaxSelect > 1 {
			schema += ".array()"
			if f.Required {
				schema += ".nonempty()"
			}
			if f.MinSelect > 0 {
				schema += fmt.Sprintf(".min(%d)", f.MinSelect)
			}
			if f.MaxSelect > 0 {
				schema += fmt.Sprintf(".max(%d)", f.MaxSelect)
			}
		}
		return schema
	case *core.JSONField:
		return fmt.Sprintf("%s: z.unknown()", name)
	case *core.GeoPointField:
		schema := fmt.Sprintf("%s: z.object({ lon: z.number(), lat: z.number() })", name)
		if f.Required {
			schema += ".refine(({ lon, lat }) => !(lon === 0 && lat === 0))"
		}
		return schema
	default:
		return fmt.Sprintf("%s: z.unknown()", name)
	}
}

func zodTextFieldSchema(f *core.TextField) string {
	schema := fmt.Sprintf("%s: z.string()", f.GetName())
	if f.Pattern != "" {
		schema += fmt.Sprintf(".regex(/%s/)", f.Pattern)
	}
	if f.Min > 0 && f.Min == f.Max {
		schema += fmt.Sprintf(".length(%d)", f.Min)
	} else {
		if f.Min > 0 {
			schema += fmt.Sprintf(".min(%d)", f.Min)
		} else if f.Required {
			schema += ".min(1)"
		}
		if f.Max > 0 {
			schema += fmt.Sprintf(".max(%d)", f.Max)
		}
	}
	return schema
}

func zodTextFieldSchemaWithName(f *core.TextField) string {
	return zodTextFieldSchema(f)
}

// ---------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------

func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	for i, part := range parts {
		if len(part) > 0 {
			runes := []rune(part)
			runes[0] = unicode.ToUpper(runes[0])
			parts[i] = string(runes)
		}
	}
	return strings.Join(parts, "")
}

func toCamelCase(s string) string {
	pascal := toPascalCase(s)
	if len(pascal) == 0 {
		return pascal
	}
	runes := []rune(pascal)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

func sameStringSlice(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func quotedJoin(strs []string) string {
	quoted := make([]string, len(strs))
	for i, s := range strs {
		quoted[i] = fmt.Sprintf(`"%s"`, s)
	}
	return strings.Join(quoted, ", ")
}

// loadEnvFile reads a .env file from the working directory (or parent) and
// sets any variables that are not already present in the environment.
func loadEnvFile() {
	envPath := ".env"
	if _, err := os.Stat(envPath); os.IsNotExist(err) {
		envPath = "../.env"
		if _, err := os.Stat(envPath); os.IsNotExist(err) {
			return
		}
	}

	data, err := os.ReadFile(envPath)
	if err != nil {
		return
	}

	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, val, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		key = strings.TrimSpace(key)
		val = strings.TrimSpace(val)
		// Strip surrounding quotes
		if len(val) >= 2 && ((val[0] == '"' && val[len(val)-1] == '"') || (val[0] == '\'' && val[len(val)-1] == '\'')) {
			val = val[1 : len(val)-1]
		}
		// Don't override existing env vars
		if _, exists := os.LookupEnv(key); !exists {
			os.Setenv(key, val)
		}
	}
}

func formatTS(input string) string {
	if !strings.Contains(input, "\n") {
		return input
	}
	lines := strings.Split(input, "\n")
	indent := 0
	var output strings.Builder
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			output.WriteString("\n")
			continue
		}
		if strings.HasSuffix(trimmed, "}") && !strings.Contains(trimmed, "{") {
			indent--
			if indent < 0 {
				indent = 0
			}
		}
		output.WriteString(strings.Repeat("    ", indent))
		output.WriteString(trimmed)
		output.WriteString("\n")
		if strings.HasSuffix(trimmed, "{") {
			indent++
		}
	}
	return output.String()
}
